name: Main
version: ${project.version}
main: de.freddy.MoneySystem.Main
api-version: 1.16
authors: [ Freddy880 ]
description: Ein Money Plugin

commands:
  heal:
    description: Dierser Befehl healt dich.
    aliases: ["healme"]
  spawn:
    description: Dieser Befehl teleportiert dich zum spawn.
    aliases: "setspawn"
  money:
    description: Mit diesem befehl kann man sein Konto verwallten
    aliases: "pay"
  sendmoney:
    description: mit diesem Befehl kann man geld automatisiert an andere schicken
  konto:
    description: mit diesem Befehl kann man Geld auf ein Konto schieben oder ein Konto erstellen
  ping:
    description: mit diesem Befehl kann der Spieler seine Ping abfragen
  message:
    description: Mit diesem befehl kann man nachrichten verschicken

permissions:
  de.freddy.MoneySystem.heal:
    description: Damit kannst du dich healen.
    default: op
  de.freddy.MoneySystem.setspawn:
    description: Damit kannst du den Spawn setzen.
    default: op
  de.freddy.moneyAdmin:
    description: Hiermit kann mann das Geld der Spieler verwallten
    default: op
  de.freddysMoney.buysing:
    description: Permission, mitder man Kaufschilder erstellen kann
    default: op
